ci: add some test in dev branch

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,5 +1,5 @@
 # .github/workflows/docker-test.yml
-name: Test Docker Image Build
+name: Test
 
 on:
   push:
@@ -57,3 +57,26 @@ jobs:
             NODE_OPTIONS=--max_old_space_size=4096
           cache-from: type=gha
           cache-to: type=gha,mode=max
+
+  test-npm:
+    name: Verify NPM_TOKEN expiriration
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          ref: main  # Ensure we're using the code from main branch after release
+          fetch-depth: 0  # Fetch all history for proper versioning
+          fetch-tags: true # Fetch all tags to ensure release tag is available
+      
+      - name: Verify NPM_TOKEN secret
+        env:
+          CHECK_TOKEN: ${{ secrets.NPM_TOKEN != '' }}
+        run: |
+          if [[ "$CHECK_TOKEN" != "true" ]]; then
+            echo "::error::NPM_TOKEN secret is not set. Cannot publish to NPM."
+            exit 1
+          else
+            echo "NPM_TOKEN secret is available"
+          fi          
